// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 robot.glb 
// */

import React, { useEffect } from 'react'
import { useGraph, type MathProps } from '@react-three/fiber'
import { useGLTF, useAnimations, useMatcapTexture } from '@react-three/drei'
import * as THREE from 'three';
import { SkeletonUtils } from 'three-stdlib'

import robotURL from './model/robot.glb';

const material = new THREE.MeshMatcapMaterial();

type GroupProps = Partial<MathProps<THREE.Group<THREE.Object3DEventMap>>>;

export type AnimationKey = 'walk' | 'idle' | 'hit';
interface Props extends GroupProps {
  animationName: AnimationKey;
}

export function Robot(props: Props) {
  const { animationName } = props;

  const group = React.useRef<THREE.Group | null>(null);
  const { scene, animations } = useGLTF(robotURL)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone)
  const { actions } = useAnimations(animations, group);
  console.log(actions);

  const [matcapTexture] = useMatcapTexture('7B5254_E9DCC7_B19986_C8AC91', 256);
  useEffect(() => {
    matcapTexture.colorSpace = THREE.SRGBColorSpace;
    matcapTexture.needsUpdate = true;

    material.matcap = matcapTexture;
    material.needsUpdate = true;
  }, []);

  useEffect(() => {
    const action = actions[animationName];
    action?.reset().fadeIn(0.5).play();
    return () => { action?.fadeOut(0.5); }
  }, [animationName]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" scale={2.514}>
          <primitive object={nodes.spine} />
          <skinnedMesh
            name="Cube"
            geometry={(nodes.Cube as any).geometry}
            material={material}
            skeleton={(nodes.Cube as any).skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(robotURL)
